function createfigure1(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%CREATEFIGURE1(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data
%  YMATRIX3:  matrix of y data
%  YMATRIX4:  matrix of y data

%  Auto-generated by MATLAB on 05-Apr-2024 09:16:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13439466612152 0.11 0.152254270048692 0.701866859623734]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',1.5);
set(plot1(1),'DisplayName',' Joint Precoding and PCS Design','Marker','x',...
    'Color',[1 0 0]);
set(plot1(2),'DisplayName','Precoding-only design','Marker','*',...
    'LineStyle','--',...
    'Color',[0 0 0]);

% Create ylabel
ylabel('SC (bits/s/Hz)','FontName','Times New Roman');

% Create xlabel
xlabel('\it P_t \rm(dBm)','FontName','Times New Roman');

% Create title
title('\rm a, 8PAM ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[30 45]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 3]);
grid(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.298392988763981 0.852175926436466 0.399999990855178 0.0404624267694809],...
    'Orientation','horizontal');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.340511687398116 0.11 0.152254270048692 0.696078147612156]);
hold(axes2,'on');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix2,'Parent',axes2,'LineWidth',1.5);
set(semilogy1(1),'Marker','x','Color',[1 0 0]);
set(semilogy1(2),'Marker','*','LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('BER','FontName','Times New Roman');

% Create xlabel
xlabel('\it P_t \rm(dBm)','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[30 45]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[1e-06 1]);
grid(axes2,'on');
% Set the remaining axes properties
set(axes2,'YMinorTick','on','YScale','log');
% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.546628708674712 0.11 0.152254270048692 0.693183791606368]);
hold(axes3,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix3,'Parent',axes3,'LineWidth',1.5);
set(plot2(1),'Marker','x','Color',[1 0 0]);
set(plot2(2),'Marker','*','LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('SC (bits/s/Hz)','FontName','Times New Roman');

% Create xlabel
xlabel('\it P_t \rm(dBm)','FontName','Times New Roman');

% Create title
title('\rm b, 16PAM ');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[30 45]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 4]);
grid(axes3,'on');
% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.752745729951308 0.11 0.152254270048692 0.690289435600579]);
hold(axes4,'on');

% Create multiple lines using matrix input to semilogy
semilogy2 = semilogy(X1,YMatrix4,'Parent',axes4,'LineWidth',1.5);
set(semilogy2(1),'Marker','x','Color',[1 0 0]);
set(semilogy2(2),'Marker','*','LineStyle','--','Color',[0 0 0]);

% Create ylabel
ylabel('BER','FontName','Times New Roman');

% Create xlabel
xlabel('\it P_t \rm(dBm)','FontName','Times New Roman');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[30 45]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[1e-06 1]);
grid(axes4,'on');
% Set the remaining axes properties
set(axes4,'YMinorTick','on','YScale','log');
